### PR TITLE
Add support for Algebraic Graphs. Fix #59

### LINKED ISSUE #59: RDF graph instance using alga
[Alga](https://github.com/snowleopard/alga) is a library for algebraic construction and manipulation of graphs in Haskell. See the Haskell 2017 paper _Algebraic Graphs with Class (Functional Pearl)_ ([link](https://dl.acm.org/authorize?N46678)).

The idea would be to implement a new module `Data.RDF.Graph.Alga`, with an implementation for all methods in the `Rdf` class, i.e.

    instance Rdf Alga where ...

### PR DESCRIPTION
**Pull request by wismill**

### CODE REVIEW

**Comment by wismill** [comment]
There is an issue with `stack` and `lts <= 12`: this PR requires `algebraic-graphs >= 0.3` and only `lts-13` fulfills it.

**Comment by robstewart57** [comment]
@wismill Thanks! There's a conflict currently in bench/MainCriterion.hs for this PR. If you're able to push a merge commit, I'll be able to merge this PR.

**Comment by wismill** [comment]
That should do!

**Comment by robstewart57** [comment]
Thanks! Any idea how it performs in the rdf4h criterion tests, compared with the existing RDF graph implementations that the library has?

**Comment by wismill** [comment]
Unfortunately, due to #61 I cannot run the benchmark. If you could send me the file or better update the benchmark with a new file.

**Comment by robstewart57** [comment]
@wismill I've uploaded a copy to Dropbox. Here it is:

https://www.dropbox.com/s/z1it340emcreowj/bills.099.actions.rdf?dl=0

**Comment by wismill** [comment]
First results do not look good: AlgebraicGraph is about 200 times _slower_ than AdjHashMap for `query`.

```
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - rdf4h-3.1.1 (bench:rdf4h-bench) (ephemeral targets)
Preprocessing benchmark 'rdf4h-bench' for rdf4h-3.1.1..
Building benchmark 'rdf4h-bench' for rdf4h-3.1.1..
Running 1 benchmarks...
Benchmark rdf4h-bench: RUNNING...
benchmarking rdf4h/parsers/ntriples-parsec
time                 100.1 ms   (95.28 ms .. 103.2 ms)
                     0.999 R²   (0.998 R² .. 1.000 R²)
mean                 99.15 ms   (97.29 ms .. 101.1 ms)
std dev              2.675 ms   (1.703 ms .. 3.370 ms)

benchmarking rdf4h/parsers/ntriples-attoparsec
time                 56.99 ms   (55.34 ms .. 58.55 ms)
                     0.996 R²   (0.988 R² .. 0.999 R²)
mean                 55.93 ms   (54.54 ms .. 57.23 ms)
std dev              2.468 ms   (2.025 ms .. 3.117 ms)

benchmarking rdf4h/parsers/turtle-parsec
time                 122.5 ms   (118.2 ms .. 127.4 ms)
                     0.998 R²   (0.995 R² .. 1.000 R²)
mean                 119.6 ms   (116.9 ms .. 121.7 ms)
std dev              4.109 ms   (3.180 ms .. 5.068 ms)
variance introduced by outliers: 11% (moderately inflated)

benchmarking rdf4h/parsers/turtle-attoparsec
time                 106.4 ms   (101.2 ms .. 109.0 ms)
                     0.998 R²   (0.995 R² .. 1.000 R²)
mean                 105.9 ms   (104.4 ms .. 107.8 ms)
std dev              3.005 ms   (2.250 ms .. 3.869 ms)

benchmarking rdf4h/query/TList SPO
time                 4.926 ms   (4.902 ms .. 4.959 ms)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 4.930 ms   (4.917 ms .. 4.953 ms)
std dev              51.82 μs   (29.38 μs .. 85.45 μs)

benchmarking rdf4h/query/TList SP
time                 1.756 ms   (1.711 ms .. 1.788 ms)
                     0.995 R²   (0.993 R² .. 0.997 R²)
mean                 1.852 ms   (1.812 ms .. 1.970 ms)
std dev              186.3 μs   (132.8 μs .. 244.4 μs)
variance introduced by outliers: 70% (severely inflated)

benchmarking rdf4h/query/TList S
time                 1.774 ms   (1.726 ms .. 1.813 ms)
                     0.995 R²   (0.993 R² .. 0.997 R²)
mean                 1.803 ms   (1.783 ms .. 1.831 ms)
std dev              86.54 μs   (74.24 μs .. 106.9 μs)
variance introduced by outliers: 34% (moderately inflated)

benchmarking rdf4h/query/TList PO
time                 2.147 ms   (2.128 ms .. 2.176 ms)
                     0.997 R²   (0.994 R² .. 0.999 R²)
mean                 2.197 ms   (2.175 ms .. 2.239 ms)
std dev              87.27 μs   (63.22 μs .. 119.4 μs)
variance introduced by outliers: 26% (moderately inflated)

benchmarking rdf4h/query/TList SO
time                 1.802 ms   (1.782 ms .. 1.828 ms)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 1.785 ms   (1.772 ms .. 1.805 ms)
std dev              53.40 μs   (38.06 μs .. 68.70 μs)
variance introduced by outliers: 16% (moderately inflated)

benchmarking rdf4h/query/TList P
time                 2.116 s    (1.855 s .. 2.224 s)
                     0.998 R²   (0.996 R² .. 1.000 R²)
mean                 2.208 s    (2.161 s .. 2.276 s)
std dev              65.96 ms   (30.88 ms .. 84.19 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking rdf4h/query/TList O
time                 1.731 ms   (1.664 ms .. 1.826 ms)
                     0.989 R²   (0.984 R² .. 0.995 R²)
mean                 1.745 ms   (1.719 ms .. 1.818 ms)
std dev              115.8 μs   (91.72 μs .. 154.1 μs)
variance introduced by outliers: 50% (severely inflated)

benchmarking rdf4h/query/AdjHashMap SPO
time                 293.7 ns   (292.7 ns .. 294.7 ns)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 295.6 ns   (294.5 ns .. 297.0 ns)
std dev              4.979 ns   (3.326 ns .. 7.237 ns)
variance introduced by outliers: 19% (moderately inflated)

benchmarking rdf4h/query/AdjHashMap SP
time                 476.7 ns   (474.2 ns .. 479.3 ns)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 476.9 ns   (474.7 ns .. 481.3 ns)
std dev              8.688 ns   (6.296 ns .. 12.75 ns)
variance introduced by outliers: 22% (moderately inflated)

benchmarking rdf4h/query/AdjHashMap S
time                 451.3 ns   (445.7 ns .. 457.0 ns)
                     0.998 R²   (0.997 R² .. 1.000 R²)
mean                 452.8 ns   (448.8 ns .. 459.1 ns)
std dev              20.28 ns   (12.83 ns .. 28.71 ns)
variance introduced by outliers: 63% (severely inflated)

benchmarking rdf4h/query/AdjHashMap PO
time                 152.6 ns   (149.1 ns .. 155.1 ns)
                     0.998 R²   (0.997 R² .. 0.999 R²)
mean                 151.6 ns   (149.5 ns .. 153.7 ns)
std dev              7.085 ns   (5.710 ns .. 9.316 ns)
variance introduced by outliers: 67% (severely inflated)

benchmarking rdf4h/query/AdjHashMap SO
time                 237.0 ns   (236.0 ns .. 238.8 ns)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 239.3 ns   (238.2 ns .. 241.4 ns)
std dev              4.969 ns   (4.047 ns .. 6.559 ns)
variance introduced by outliers: 27% (moderately inflated)

benchmarking rdf4h/query/AdjHashMap P
time                 1.984 ms   (1.967 ms .. 2.023 ms)
                     0.995 R²   (0.985 R² .. 0.999 R²)
mean                 2.055 ms   (2.021 ms .. 2.099 ms)
std dev              119.2 μs   (71.51 μs .. 178.4 μs)
variance introduced by outliers: 42% (moderately inflated)

benchmarking rdf4h/query/AdjHashMap O
time                 131.0 ns   (113.3 ns .. 152.0 ns)
                     0.915 R²   (0.862 R² .. 1.000 R²)
mean                 118.6 ns   (114.2 ns .. 127.7 ns)
std dev              22.60 ns   (4.298 ns .. 41.00 ns)
variance introduced by outliers: 97% (severely inflated)

benchmarking rdf4h/query/AlgebraicGraph SPO
time                 54.25 ms   (48.37 ms .. 57.33 ms)
                     0.986 R²   (0.967 R² .. 0.997 R²)
mean                 55.80 ms   (51.30 ms .. 59.16 ms)
std dev              6.819 ms   (3.410 ms .. 10.61 ms)
variance introduced by outliers: 40% (moderately inflated)

benchmarking rdf4h/query/AlgebraicGraph SP
time                 55.44 ms   (52.14 ms .. 59.00 ms)
                     0.992 R²   (0.985 R² .. 0.997 R²)
mean                 54.29 ms   (49.11 ms .. 56.87 ms)
std dev              6.283 ms   (2.417 ms .. 9.800 ms)
variance introduced by outliers: 40% (moderately inflated)

benchmarking rdf4h/query/AlgebraicGraph S
time                 62.13 ms   (57.38 ms .. 64.35 ms)
                     0.994 R²   (0.982 R² .. 0.998 R²)
mean                 59.00 ms   (53.35 ms .. 61.57 ms)
std dev              6.758 ms   (3.350 ms .. 10.35 ms)
variance introduced by outliers: 40% (moderately inflated)

benchmarking rdf4h/query/AlgebraicGraph PO
time                 61.21 ms   (52.67 ms .. 68.96 ms)
                     0.963 R²   (0.900 R² .. 0.989 R²)
mean                 64.14 ms   (58.14 ms .. 69.82 ms)
std dev              10.67 ms   (6.266 ms .. 17.32 ms)
variance introduced by outliers: 53% (severely inflated)

benchmarking rdf4h/query/AlgebraicGraph SO
time                 70.40 ms   (64.64 ms .. 74.47 ms)
                     0.989 R²   (0.968 R² .. 0.999 R²)
mean                 62.24 ms   (55.56 ms .. 65.31 ms)
std dev              8.229 ms   (3.435 ms .. 13.67 ms)
variance introduced by outliers: 44% (moderately inflated)

benchmarking rdf4h/query/AlgebraicGraph P
time                 73.25 ms   (69.54 ms .. 77.29 ms)
                     0.992 R²   (0.980 R² .. 0.998 R²)
mean                 69.58 ms   (64.65 ms .. 73.07 ms)
std dev              7.055 ms   (4.436 ms .. 10.08 ms)
variance introduced by outliers: 35% (moderately inflated)

benchmarking rdf4h/query/AlgebraicGraph O
time                 99.12 ms   (86.62 ms .. 114.5 ms)
                     0.953 R²   (0.877 R² .. 0.996 R²)
mean                 88.50 ms   (80.63 ms .. 97.53 ms)
std dev              12.86 ms   (6.193 ms .. 21.43 ms)
variance introduced by outliers: 43% (moderately inflated)

benchmarking rdf4h/select/TList SPO
time                 5.755 ms   (5.629 ms .. 5.992 ms)
                     0.991 R²   (0.983 R² .. 0.997 R²)
mean                 6.205 ms   (6.083 ms .. 6.322 ms)
std dev              377.4 μs   (337.2 μs .. 455.4 μs)
variance introduced by outliers: 35% (moderately inflated)

benchmarking rdf4h/select/TList SP
time                 2.167 s    (1.277 s .. 2.741 s)
                     0.982 R²   (0.938 R² .. 1.000 R²)
mean                 2.297 s    (2.115 s .. 2.591 s)
std dev              297.1 ms   (125.1 ms .. 412.0 ms)
variance introduced by outliers: 24% (moderately inflated)

benchmarking rdf4h/select/TList S
time                 2.137 s    (1.527 s .. 2.652 s)
                     0.991 R²   (0.980 R² .. 1.000 R²)
mean                 2.137 s    (2.089 s .. 2.231 s)
std dev              91.05 ms   (10.67 ms .. 109.7 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking rdf4h/select/TList PO
time                 2.690 ms   (2.667 ms .. 2.724 ms)
                     0.998 R²   (0.996 R² .. 1.000 R²)
mean                 2.698 ms   (2.682 ms .. 2.723 ms)
std dev              77.91 μs   (43.62 μs .. 118.6 μs)
variance introduced by outliers: 15% (moderately inflated)

benchmarking rdf4h/select/TList SO
time                 1.760 ms   (1.744 ms .. 1.779 ms)
                     0.998 R²   (0.995 R² .. 1.000 R²)
mean                 1.779 ms   (1.763 ms .. 1.805 ms)
std dev              56.59 μs   (32.43 μs .. 86.96 μs)
variance introduced by outliers: 19% (moderately inflated)

benchmarking rdf4h/select/TList P
time                 14.10 s    (10.50 s .. 16.76 s)
                     0.969 R²   (0.954 R² .. 1.000 R²)
mean                 11.54 s    (10.84 s .. 12.89 s)
std dev              1.325 s    (36.55 ms .. 1.619 s)
variance introduced by outliers: 23% (moderately inflated)

benchmarking rdf4h/select/TList O
time                 1.322 s    (1.121 s .. 1.541 s)
                     0.995 R²   (0.994 R² .. 1.000 R²)
mean                 1.446 s    (1.381 s .. 1.482 s)
std dev              62.78 ms   (16.96 ms .. 84.69 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking rdf4h/select/AdjHashMap SPO
time                 1.396 ms   (1.371 ms .. 1.465 ms)
                     0.978 R²   (0.927 R² .. 0.999 R²)
mean                 1.423 ms   (1.396 ms .. 1.489 ms)
std dev              148.4 μs   (60.85 μs .. 266.8 μs)
variance introduced by outliers: 72% (severely inflated)

benchmarking rdf4h/select/AdjHashMap SP
time                 1.869 ms   (1.833 ms .. 1.943 ms)
                     0.983 R²   (0.958 R² .. 0.999 R²)
mean                 1.873 ms   (1.837 ms .. 1.957 ms)
std dev              163.4 μs   (62.77 μs .. 286.3 μs)
variance introduced by outliers: 63% (severely inflated)

benchmarking rdf4h/select/AdjHashMap S
time                 1.731 ms   (1.689 ms .. 1.800 ms)
                     0.980 R²   (0.951 R² .. 0.999 R²)
mean                 1.781 ms   (1.750 ms .. 1.866 ms)
std dev              175.5 μs   (101.1 μs .. 312.8 μs)
variance introduced by outliers: 69% (severely inflated)

benchmarking rdf4h/select/AdjHashMap PO
time                 258.0 μs   (248.5 μs .. 278.5 μs)
                     0.974 R²   (0.936 R² .. 0.997 R²)
mean                 262.3 μs   (254.0 μs .. 276.2 μs)
std dev              39.52 μs   (26.30 μs .. 54.92 μs)
variance introduced by outliers: 90% (severely inflated)

benchmarking rdf4h/select/AdjHashMap SO
time                 1.281 ms   (1.244 ms .. 1.337 ms)
                     0.975 R²   (0.938 R² .. 0.998 R²)
mean                 1.294 ms   (1.270 ms .. 1.336 ms)
std dev              146.6 μs   (70.27 μs .. 252.3 μs)
variance introduced by outliers: 76% (severely inflated)

benchmarking rdf4h/select/AdjHashMap P
time                 3.835 ms   (3.730 ms .. 3.976 ms)
                     0.986 R²   (0.971 R² .. 0.997 R²)
mean                 3.808 ms   (3.752 ms .. 3.913 ms)
std dev              259.3 μs   (153.5 μs .. 391.4 μs)
variance introduced by outliers: 44% (moderately inflated)

benchmarking rdf4h/select/AdjHashMap O
time                 1.004 ms   (986.3 μs .. 1.041 ms)
                     0.987 R²   (0.970 R² .. 0.999 R²)
mean                 1.010 ms   (988.9 μs .. 1.048 ms)
std dev              83.29 μs   (32.98 μs .. 134.1 μs)
variance introduced by outliers: 64% (severely inflated)

benchmarking rdf4h/select/AlgebraicGraph SPO
time                 65.97 ms   (59.80 ms .. 73.14 ms)
                     0.969 R²   (0.894 R² .. 0.997 R²)
mean                 61.81 ms   (56.36 ms .. 66.33 ms)
std dev              8.401 ms   (4.924 ms .. 11.78 ms)
variance introduced by outliers: 44% (moderately inflated)

benchmarking rdf4h/select/AlgebraicGraph SP
time                 78.68 ms   (70.82 ms .. 90.86 ms)
                     0.970 R²   (0.954 R² .. 0.996 R²)
mean                 69.51 ms   (59.24 ms .. 74.17 ms)
std dev              10.51 ms   (6.622 ms .. 15.79 ms)
variance introduced by outliers: 53% (severely inflated)

benchmarking rdf4h/select/AlgebraicGraph S
time                 81.31 ms   (69.99 ms .. 94.59 ms)
                     0.957 R²   (0.871 R² .. 0.994 R²)
mean                 89.20 ms   (83.37 ms .. 96.60 ms)
std dev              10.30 ms   (5.903 ms .. 13.63 ms)
variance introduced by outliers: 38% (moderately inflated)

benchmarking rdf4h/select/AlgebraicGraph PO
time                 72.14 ms   (60.72 ms .. 81.05 ms)
                     0.968 R²   (0.880 R² .. 0.995 R²)
mean                 81.48 ms   (75.84 ms .. 87.25 ms)
std dev              10.01 ms   (6.995 ms .. 14.11 ms)
variance introduced by outliers: 38% (moderately inflated)

benchmarking rdf4h/select/AlgebraicGraph SO
time                 72.27 ms   (66.38 ms .. 77.73 ms)
                     0.971 R²   (0.915 R² .. 0.997 R²)
mean                 68.86 ms   (64.13 ms .. 74.32 ms)
std dev              9.268 ms   (6.032 ms .. 16.15 ms)
variance introduced by outliers: 44% (moderately inflated)

benchmarking rdf4h/select/AlgebraicGraph P
time                 94.67 ms   (87.10 ms .. 103.2 ms)
                     0.987 R²   (0.974 R² .. 0.998 R²)
mean                 90.63 ms   (81.74 ms .. 95.85 ms)
std dev              10.50 ms   (4.722 ms .. 15.76 ms)
variance introduced by outliers: 32% (moderately inflated)

benchmarking rdf4h/select/AlgebraicGraph O
time                 96.45 ms   (76.53 ms .. 109.1 ms)
                     0.959 R²   (0.901 R² .. 0.993 R²)
mean                 99.88 ms   (89.07 ms .. 109.9 ms)
std dev              19.12 ms   (11.12 ms .. 28.49 ms)
variance introduced by outliers: 65% (severely inflated)

benchmarking rdf4h/add-remove-triples/TList-add-triples
time                 5.363 ms   (4.233 ms .. 6.472 ms)
                     0.803 R²   (0.619 R² .. 0.906 R²)
mean                 5.723 ms   (5.327 ms .. 6.114 ms)
std dev              1.315 ms   (1.083 ms .. 1.724 ms)
variance introduced by outliers: 89% (severely inflated)

benchmarking rdf4h/add-remove-triples/TList-remove-triples
```

**Pull request merged**
