### PR TITLE
Support fgl-5.5

### PR DESCRIPTION
**Pull request by ddssff**
This adds an #ifdef of an NFData instance that got added to fgl-5.5.

### CODE REVIEW

**Comment by robstewart57** [comment]
Thanks for finding this. The NFData instance was not in fgl 5.5.1.0 but arrived in 5.5.2.0. Rather than an #ifdef to add the NFData instance within rdf4h for fgl <= 5.5.1.0 , should we instead just remove the NFData instance in rdf4h and bump the fgl lower bound to 5.5.2.0 ?

**Comment by ddssff** [comment]
Yes, pushing the lower bound would be better, ifdefs are a long term pain.

**Comment by ddssff** [comment]
I will close this and make a new patch.

**Comment by robstewart57** [comment]
Thanks!

**Pull request closed without merging**
