### PR TITLE
WIP: fixing tests

### PR DESCRIPTION
**Pull request by wismill**
This PR is a work in progress to reach a better conformance to the W3C standards.
I have focused mainly on Turtle parser. Lots of fixes are related to the handling of escape sequences and file encoding. However, I think the NTriples parser deserves more testing.
I have not focused much on the performance yet. I think correctness is most important. Once tests are fixed, I would like to propose to select a unique modern parser library (Attoparsec or Megaparsec) to improve the performance, in another PR.

### CODE REVIEW

**Comment by wismill** [comment]
About 45 tests failure were fixed. Remaining: 57

**Comment by robstewart57** [comment]
This is superb :)

Would you like me to merge this PR?

**Comment by wismill** [comment]
Not yet, I keep improving the code and fixing test failures.

**Comment by wismill** [comment]
@robstewart57 I have made some breaking changes.
- I will try to restore as much as possible functions with a deprecation warning, if you agree with that.
- The handling of the escape sequences are incompatible with previous version (they were not unescaped).
- This library fully supports IRI, not only URI. I have started to rename things to avoid misunderstanding.
- The resolution of the IRI was confusing. As I understood, the standard RFC states the following precedence on the base IRI: embedded > parsing context > doc iri > application default. I have modified the 1st conformance test so.

I would be glad to have your feedback on it.

**Comment by wismill** [comment]
50 out of 1177 tests failed (35.85s)
The remaing tests are mostly about XML. I do not think I will have the time soon to check them.
Maybe now the focus should be on the performance.

**Comment by robstewart57** [comment]
Great, many of the turtle parser tests have been fixed.

Ignore the XML parser tests for now, since some of the tests failures are
to do with how they are set up (the definition of the base URL in some of
them is wrong). I'll get round to fixing the XML parser tests soon, and
I'll ping you once this has been done.

**Comment by robstewart57** [comment]
I agree that once the Turtle and NT parsers pass all W3C unit tests then Turtle and NT parser performance is a good secondary goal.

**Comment by wismill** [comment]
1 test fixed (_49 out of 1177 tests failed_). But for some reason, test `turtle-subm-14` keep failing with `lts-6` and `lts-7`. Must be a bug with some package, because I do not observe this on my machine using `cabal new-test --with-ghc <GHC_PATH>`.

The remaining failing test are only related to XML.

@robstewart57 ready for complete review.

**Comment by robstewart57** [comment]
Excellent. IRI support is a great new feature, With lts 12.1 I'm also able to replicate the absence of failing Turtle or NT W3C parser tests with your branch :) I'll merge and update the documentation.

**Pull request merged**
