### PR TITLE
Update XmlParser.hs

### PR DESCRIPTION
**Pull request by jrp2014**
Comment in the middle of an expression seems to break build

### CODE REVIEW

**Comment by jrp2014** [comment]
OK. This gets us to failing runtime tests, rather than failing compile time syntax errors.

**Comment by wismill** [comment]
I stumbled against this issue as well. It is now fixed in master.

**Comment by robstewart57** [comment]
@wismill so I could close this PR?

**Comment by wismill** [comment]
@robstewart57 Yes it can be closed.

**Comment by robstewart57** [comment]
The RDF/XML parser has been replaced by an xmlbf based re-implementation.

https://github.com/robstewart57/rdf4h/commit/eca4daefccaf005e36f2e831b966ef7ba8512258

Closing this PR.

**Pull request closed without merging**
